name: Zip file
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gulas2vladimir/action-zip@v1
    - name: Archive Release
      with:
        filename: 'release.zip'

