name: Zip file
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macos
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r release.zip QuickPass.app
    - name: Release to Github
      run: echo "Release"